WELCOME_MSG='Hi welcome! \n\nStart the deamon using: \n/{}  <SYMBOL> <POLLING_SECONDS>'
HELP_MSG='Want to know more about Trading-Deamon? \nClick <a href="{}">here</a>'
WRONG_COMMAND_MSG='Wrong command used'
OK_CONFIGURATION_MSG='Bot new configurations were updated correctly.'
START_MSG='Daemon is going background: \nSYMBOL={} \nPOLLING_SECONDS={}'
FINISH_MSG= 'Daemon is stopping. \n\n{} prices over the deamon alive period: {} \n'
ALREADY_RUNNING_MSG= 'Daemon is already running in background. Plese wait for it to finish its previous search.'
STOPPING_NONEEDED__MSG= 'Daemon is terminating or already stopped! No need to stop it.'
STOPPING_MSG= 'Daemon is now terminating. It could take up to 60 seconds.'
