WELCOME_MSG='Hi welcome! \n\nFirst: configure your deamon using: \n/{} <TICKER> <POLLING_SECONDS>'
HELP_MSG='Want to know more about Trading-Deamon? \nClick <a href="{}">here</a>'
WRONG_COMMAND_MSG='Wrong command used'
KO_CONFIGURATION_MSG='Wrong parameters passed. \n\n The bot is now using default values. \nTICKER={}, \nSLEEP_SECONDS={}'
OK_CONFIGURATION_MSG='Bot new configurations were updated correctly'
FINISH_MSG= 'Daemon is stopping. \n\n{} prices over the deamon alive period: {} \n {}'